export type FilterState = {
  title: string | null;
  state: string | null;
  lga: string | null;
};

export const artisanTitles = [
  "Carpenter",
  "Makeup Artist",
  "Auto Mechanic",
  "Caterer",
  "Mason",
  "Electronics Repairer",
  "Hair Stylist",
  "Electrician",
  "Event Decorator",
  "Painter",
  "Tailor",
  "Nail Technician",
  "Welder",
  "Plumber",
  "Henna Artist",
  "Technician",
  "Bead Maker",
  "Tiler",
  "Fashion Designer",
  "Solar Installer",
] as const;

export const statesWithLgas = {
  Abia: [],
  Adamawa: [],
  AkwaIbom: [],
  Anambra: ["Awka South", "Onitsha South"],
  Bauchi: [],
  Bayelsa: [],
  Benue: [],
  Borno: [],
  CrossRiver: [],
  Delta: ["Asaba"],
  Ebonyi: [],
  Edo: [],
  Ekiti: [],
  Enugu: ["Nsukka"],
  Gombe: [],
  Imo: [],
  Jigawa: [],
  Kaduna: ["Zaria", "Chikun"],
  Kano: ["Tarauni"],
  Katsina: [],
  Kebbi: ["Birnin Kebbi"],
  Kogi: ["Lokoja"],
  Kwara: ["Ilorin West"],
  Lagos: ["Ikeja", "Epe", "Surulere", "Mushin", "Ikorodu", "Oshodi"],
  Nasarawa: ["Keffi"],
  Niger: [],
  Ogun: ["Abeokuta South"],
  Ondo: [],
  Osun: [],
  Oyo: [],
  Plateau: ["Jos North"],
  Rivers: [],
  Sokoto: ["Sokoto South"],
  Taraba: [],
  Yobe: [],
  Zamfara: [],
  Abuja: ["Gwagwalada"],
} as const;

// This array is typed as const so you can use it safely for dropdowns, type inference, or filtering in TypeScript.

export const artisanData = [
  {
    id: "1",
    name: "Tolu Crafts",
    image: "/woodwork.jpg",
    bio: "Woodworking and rustic designs.",
    title: "Carpenter",
    lga: "Gwagwalada",
    state: "Abuja",
    rating: 4.5,
  },
  {
    id: "2",
    name: "Ada's Touch",
    image: "/mua.jpg",
    bio: "Luxury bridal makeup and skin glow specialist.",
    title: "Makeup Artist",
    lga: "Ikeja",
    state: "Lagos",
    rating: 5,
  },
  {
    id: "3",
    name: "Ola's Mechanics",
    image: "/mechanic.jpg",
    bio: "Mobile car mechanic with fast response times.",
    title: "Auto Mechanic",
    lga: "Mushin",
    state: "Lagos",
    rating: 4,
  },
  {
    id: "4",
    name: "Kemi Cooks",
    image: "/chef.jpg",
    bio: "Catering for all your party needs with a local twist.",
    title: "Caterer",
    lga: "Ilorin West",
    state: "Kwara",
    rating: 4.2,
  },
  {
    id: "5",
    name: "Emeka Builders",
    image: "/mason.jpg",
    bio: "House construction and remodeling expert.",
    title: "Mason",
    lga: "Awka South",
    state: "Anambra",
    rating: 4.7,
  },
  {
    id: "6",
    name: "Yusuf TechFix",
    image: "/techfix.jpg",
    bio: "Gadget repair and electronics wizard.",
    title: "Electronics Repairer",
    lga: "Tarauni",
    state: "Kano",
    rating: 4.8,
  },
  {
    id: "7",
    name: "Blessing Braids",
    image: "/hairdresser.jpg",
    bio: "Home service braider & hair stylist.",
    title: "Hair Stylist",
    lga: "Jos North",
    state: "Plateau",
    rating: 4.6,
  },
  {
    id: "8",
    name: "Bayo Electric",
    image: "/electrician.jpg",
    bio: "Certified electrician for home and office.",
    title: "Electrician",
    lga: "Surulere",
    state: "Lagos",
    rating: 4.4,
  },
  {
    id: "9",
    name: "Amina Decor",
    image: "/event-planner.jpg",
    bio: "Event decoration for weddings and birthdays.",
    title: "Event Decorator",
    lga: "Zaria",
    state: "Kaduna",
    rating: 5,
  },
  {
    id: "10",
    name: "Sule Paints",
    image: "/painter.jpeg",
    bio: "Interior and exterior painting expert.",
    title: "Painter",
    lga: "Lokoja",
    state: "Kogi",
    rating: 4.3,
  },
  {
    id: "11",
    name: "Ngozi Tailoring",
    image: "/tailor.jpg",
    bio: "Bespoke tailoring with African flair.",
    title: "Tailor",
    lga: "Onitsha South",
    state: "Anambra",
    rating: 4.9,
  },
  {
    id: "12",
    name: "Tina Nails",
    image: "/nail-tech.jpg",
    bio: "Classy nails, home service available.",
    title: "Nail Technician",
    lga: "Ikorodu",
    state: "Lagos",
    rating: 4.5,
  },
  {
    id: "13",
    name: "Daniel's Welding",
    image: "/weld.jpg",
    bio: "Metal gates and welding perfection.",
    title: "Welder",
    lga: "Epe",
    state: "Lagos",
    rating: 4.1,
  },
  {
    id: "14",
    name: "Chuks Plumbing",
    image: "/plumber.jpg",
    bio: "Plumbing repairs and installations.",
    title: "Plumber",
    lga: "Asaba",
    state: "Delta",
    rating: 4.6,
  },
  {
    id: "15",
    name: "Rashida Henna",
    image: "/henna.jpg",
    bio: "Beautiful henna artistry for any event.",
    title: "Henna Artist",
    lga: "Sokoto South",
    state: "Sokoto",
    rating: 4.8,
  },
  {
    id: "16",
    name: "Ebuka Tech",
    image: "/techfix.jpg",
    bio: "Laptop and phone repair specialist.",
    title: "Technician",
    lga: "Nsukka",
    state: "Enugu",
    rating: 4.7,
  },
  {
    id: "17",
    name: "Grace Beads",
    image: "/bead-maker.jpg",
    bio: "Handmade bead jewelry and accessories.",
    title: "Bead Maker",
    lga: "Oshodi",
    state: "Lagos",
    rating: 4.2,
  },
  {
    id: "18",
    name: "Lekan Tiles",
    image: "/tiler.jpg",
    bio: "Perfect tile laying and floor polishing.",
    title: "Tiler",
    lga: "Abeokuta South",
    state: "Ogun",
    rating: 4.3,
  },
  {
    id: "19",
    name: "Fatima Fashion",
    image: "/tailor.jpg",
    bio: "Ready-to-wear and custom fashion brand.",
    title: "Fashion Designer",
    lga: "Keffi",
    state: "Nasarawa",
    rating: 5,
  },
  {
    id: "20",
    name: "Ibrahim Solar",
    image: "/electrician.jpg",
    bio: "Affordable solar installation and repairs.",
    title: "Solar Installer",
    lga: "Birnin Kebbi",
    state: "Kebbi",
    rating: 4.9,
  },
];
